#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'real-robocar-rviz','console_scripts','real_state_pub'
__requires__ = 'real-robocar-rviz'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('real-robocar-rviz', 'console_scripts', 'real_state_pub')()
    )
